### ISSUE TITLE
The testedness command resulted in IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mzw** [mzw/VTR#5]
I faced on the following exception when running the `cluster testedness` command.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jsoup.select.Elements.get(Elements.java:544)
	at jp.mzw.vtr.cluster.testedness.Testedness.getNumOfKilledMutants(Testedness.java:264)
	at jp.mzw.vtr.cluster.testedness.Testedness.compare(Testedness.java:158)
	at jp.mzw.vtr.cluster.testedness.Testedness.run(Testedness.java:101)
	at jp.mzw.vtr.command.ClusterCommand.testedness(ClusterCommand.java:78)
	at jp.mzw.vtr.command.ClusterCommand.command(ClusterCommand.java:35)
	at jp.mzw.vtr.CLI.main(CLI.java:48)
```

**Comment by mzw** [comment]
When Jacoco and Pitest do not output any reports,  `getJacocoReport ` and `getPitestReport` methods respectively return empty strings "". The `getCoverageScore ` and `getMutationScore` were designed to parse the empty strings as the HTML-formatted contents. Thus `IndexOutOfBoundsException` occurred because the empty strings do not contain HTML elements indicating coverage and mutation scores.

https://github.com/mzw/VTR/commit/f6170aa38e16593820e22b85caa0f5053ede04a7
